[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.zip', 'nodejs_22']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm ci',
  'npm run build'
]

[phases.build]
cmds = [
  'mkdir -p storage/framework/views storage/framework/cache storage/framework/sessions',
  'chmod -R 775 storage bootstrap/cache'
]

